---
thingsWsEndpoint: "wss://things.eu-1.bosch-iot-suite.com/ws/2"
#thingsWsEndpoint: "ws://localhost:8080/ws/2"

#bearerToken: 

#oAuth:
#  tokenUrl: https://access.bosch-iot-suite.com/token
#  client:
#  secret:
#  scope:

#basicAuth:
#  user:
#  password:

#namespaces:
#  - namespace1
#  - namespace2

#pageSize: 11

#filter: in(policyId, ...)

migrations:
  - replaceSubject:
      old:
        label: DEFAULT
        subject: integration:solution-id:suffix
        ignoreMissing: true
      new:
        label: DEFAULT
        subject: integration:solution-id:suffix
        value:
          type: "migration"

logging:
  file:
    level: ERROR # Log level for logging to file (DEBUG, INFO, WARNING, ERROR, CRITICAL, NOTSET)
    filename: ./migration.log # Log filename
  console:
    level: DEBUG # Log level for logging to console (DEBUG, INFO, WARNING, ERROR, CRITICAL, NOTSET)
